DEFAULT_CANDIDATES = [
    {
        "name": "Arjun Mehta",
        "title": "Senior Full-Stack Engineer",
        "location": "Bangalore",
        "experience": 7,
        "skills": ["Python", "Flask", "React", "PostgreSQL", "AWS", "Docker", "Redis"],
        "summary": "Led platform rebuilds at two unicorn startups. Strong system design background.",
        "preferences": {"motivation": "Looking for high-ownership roles in product-led companies.", "locations": ["Bangalore", "Remote"]},
    },
    {
        "name": "Priya Sharma",
        "title": "ML Engineer",
        "location": "Hyderabad",
        "experience": 5,
        "skills": ["Python", "TensorFlow", "PyTorch", "MLOps", "Kubernetes", "SQL", "NLP"],
        "summary": "Published 2 NLP papers. Built recommendation systems serving 50M users.",
        "preferences": {"motivation": "Excited by applied ML with real-world impact.", "locations": ["Hyderabad", "Remote"]},
    },
    {
        "name": "Rohan Das",
        "title": "Frontend Engineer",
        "location": "Pune",
        "experience": 4,
        "skills": ["React", "TypeScript", "Next.js", "CSS", "Jest", "Figma"],
        "summary": "Design-system obsessed. Built component libraries used by 20+ internal teams.",
        "preferences": {"motivation": "Loves crafting accessible, performant UIs.", "locations": ["Pune", "Remote"]},
    },
    {
        "name": "Kavya Nair",
        "title": "DevOps / SRE",
        "location": "Chennai",
        "experience": 6,
        "skills": ["Kubernetes", "Terraform", "AWS", "CI/CD", "Prometheus", "Python", "Linux"],
        "summary": "Reduced infra costs by 40% at previous company. 99.99% uptime track record.",
        "preferences": {"motivation": "Passionate about reliability and infrastructure-as-code.", "locations": ["Chennai", "Remote"]},
    },
    {
        "name": "Vikram Singh",
        "title": "Backend Engineer",
        "location": "Delhi",
        "experience": 8,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Kafka", "AWS", "Docker", "Redis"],
        "summary": "Architected payment systems processing $2B/year. Expert in distributed systems.",
        "preferences": {"motivation": "Enjoys solving hard scalability challenges.", "locations": ["Delhi", "Gurugram", "Remote"]},
    },
    {
        "name": "Ananya Krishnan",
        "title": "Data Engineer",
        "location": "Bangalore",
        "experience": 3,
        "skills": ["Python", "SQL", "Airflow", "dbt", "Snowflake", "Azure"],
        "summary": "Built data pipelines processing 10TB daily. Passionate about data quality.",
        "preferences": {"motivation": "Wants to work in a data-first engineering culture.", "locations": ["Bangalore", "Remote"]},
    },
    {
        "name": "Siddharth Rao",
        "title": "Product Engineer",
        "location": "Mumbai",
        "experience": 5,
        "skills": ["Python", "Flask", "React", "PostgreSQL", "AWS", "TypeScript", "Redis"],
        "summary": "Shipped 3 products from 0→1 at early-stage startups. Comfortable across the stack.",
        "preferences": {"motivation": "Thrives in fast-paced 0-to-1 environments.", "locations": ["Mumbai", "Remote"]},
    },
    {
        "name": "Meera Pillai",
        "title": "Backend Engineer",
        "location": "Kochi",
        "experience": 4,
        "skills": ["Python", "Django", "PostgreSQL", "Docker", "AWS", "REST API"],
        "summary": "Built APIs serving 5M+ DAU. Strong on testing and code quality.",
        "preferences": {"motivation": "Values clean architecture and collaborative teams.", "locations": ["Kochi", "Remote"]},
    },
    {
        "name": "Aditya Gupta",
        "title": "Security Engineer",
        "location": "Hyderabad",
        "experience": 6,
        "skills": ["Python", "AWS", "Linux", "CI/CD", "Docker", "Kubernetes"],
        "summary": "Certified OSCP. Secured fintech platforms for 5M+ users.",
        "preferences": {"motivation": "Interested in platform and infrastructure security.", "locations": ["Hyderabad", "Remote"]},
    },
    {
        "name": "Divya Reddy",
        "title": "Full-Stack Engineer",
        "location": "Bangalore",
        "experience": 5,
        "skills": ["Python", "Flask", "React", "PostgreSQL", "Docker", "TypeScript", "AWS"],
        "summary": "Rebuilt checkout flows increasing conversion by 18%. Comfortable owning features end-to-end.",
        "preferences": {"motivation": "Enjoys full ownership of product features.", "locations": ["Bangalore", "Remote"]},
    },
]